name: Build and Deploy extension files

on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Zip
        run: |
          mkdir -p output
          cd extension
          zip -r ../output/release.xpi ./*
          cd ..

      - name: updates.json
        run: |
          VERSION=$(jq -r '.version' extension/manifest.json)
          EXT=$(jq -r '.browser_specific_settings.gecko.id' extension/manifest.json)
          REPOWNER="${{ github.repository_owner }}"
          REPONAME="${{ github.event.repository.name }}"
          cat > output/updates.json <<EOF 
          {
            "addons": {
              "$EXT": {
                "updates": [
                  {
                    "version": "$VERSION",
                    "update_link": "https://$REPOWNER.github.io/$REPONAME/release.xpi"
                  }
                ]
              }
            }
          }
          EOF
      
      - name: Deploy
        run: |
          cat output/updates.json
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global user.name = "autobuild"
          git config --global user.email = "none@autobuild"
          git checkout -b versions
          git rm -rf . || true
          ls
          ls output
          cp -r output/* .
          ls
          ls output
          rm -r output
          git add .
          git commit -m "new release"
          git push --force origin versions
          ls
          ls output