name: Build and Deploy extension files

on:
  push:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Zip
        run: |
          mkdir -p output
          cd extension
          zip -r ../output/release.xpi ./*
          cd ..

      - name: updates.json
        run: |
          VERSION=$(jq -r '.version' extension/manifest.json)
          EXT=$(jq -r '.browser_specific_settings.gecko.id' extension/manifest.json)
          REPOWNER="${{ github.repository_owner }}"
          REPPNAME="${{ github.event.repository.name }}"
          cat > output/updates.json <<EOF 
          {
            "addons": {
              "$EXT": {
                "updates": [
                  {
                    "version": "$VERSION",
                    "update_link": "https://$REPOWNER.github.io/$REPNAME/release.xpi"
                  }
                ]
              }
            }
          }
          EOF
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: versions